// <auto-generated />
using System;
using LearnHubBackOffice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnHubBO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240623154849_AddCoursUtilisateur")]
    partial class AddCoursUtilisateur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnHubBO.Models.Chapitre", b =>
                {
                    b.Property<int>("IdChapitre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChapitre"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreationChapitre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModificationChapitre")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCours")
                        .HasColumnType("int");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<string>("TitreChapitre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChapitre");

                    b.HasIndex("IdCours");

                    b.ToTable("Chapitres");
                });

            modelBuilder.Entity("LearnHubBO.Models.CoursUtilisateur", b =>
                {
                    b.Property<int>("IdCoursUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCoursUtilisateur"));

                    b.Property<DateTime>("DateCreationCoursUtilisateur")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCours")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdCoursUtilisateur");

                    b.HasIndex("IdCours");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("CoursUtilisateur");
                });

            modelBuilder.Entity("LearnHubBackOffice.Models.Cours", b =>
                {
                    b.Property<int>("IdCours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCours"));

                    b.Property<DateTime>("DateCreationCours")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModificationCours")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCoursCategorie")
                        .HasColumnType("int");

                    b.Property<int>("IdFormateur")
                        .HasColumnType("int");

                    b.Property<string>("TitreCours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCours");

                    b.HasIndex("IdCoursCategorie");

                    b.HasIndex("IdFormateur");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("LearnHubBackOffice.Models.CoursCategorie", b =>
                {
                    b.Property<int>("IdCoursCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCoursCategorie"));

                    b.Property<string>("NomCoursCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCoursCategorie");

                    b.ToTable("CoursCategories");
                });

            modelBuilder.Entity("LearnHubBackOffice.Models.Formateur", b =>
                {
                    b.Property<int>("IdFormateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormateur"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomFormateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFormateur");

                    b.ToTable("Formateurs");
                });

            modelBuilder.Entity("LearnHubBackOffice.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("LearnHubBO.Models.Chapitre", b =>
                {
                    b.HasOne("LearnHubBackOffice.Models.Cours", "Cours")
                        .WithMany()
                        .HasForeignKey("IdCours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");
                });

            modelBuilder.Entity("LearnHubBO.Models.CoursUtilisateur", b =>
                {
                    b.HasOne("LearnHubBackOffice.Models.Cours", "Cours")
                        .WithMany()
                        .HasForeignKey("IdCours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnHubBackOffice.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("LearnHubBackOffice.Models.Cours", b =>
                {
                    b.HasOne("LearnHubBackOffice.Models.CoursCategorie", "CoursCategorie")
                        .WithMany()
                        .HasForeignKey("IdCoursCategorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnHubBackOffice.Models.Formateur", "Formateur")
                        .WithMany()
                        .HasForeignKey("IdFormateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoursCategorie");

                    b.Navigation("Formateur");
                });
#pragma warning restore 612, 618
        }
    }
}
